# Generated by Django 4.1.1 on 2023-05-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="icon",
            field=models.ImageField(
                default="icons/default_icon.png", upload_to="icons/"
            ),
        ),
    ]
